spring:
  application:
    name: lolwatcher
  datasource:
    url: jdbc:mysql://localhost:3306/lolwatcher
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver



riot:
  lol:
    url: https://asia.api.riotgames.com  #?? ??? ??? ???? ??.
    api-key: ${RIOT_API_KEY}
